server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oct27?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=America/Los_Angeles&allowPublicKeyRetrieval=True
    username: root
    password: Celtics119.
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    ddl-auto: update
    generate-ddl: true